// Code generated by Kitex v0.16.1. DO NOT EDIT.

package storageservice

import (
	service "Storage/kitex_gen/storage/service"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CheckOrder": kitex.NewMethodInfo(
		checkOrderHandler,
		newStorageServiceCheckOrderArgs,
		newStorageServiceCheckOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	storageServiceServiceInfo                = NewServiceInfo()
	storageServiceServiceInfoForClient       = NewServiceInfoForClient()
	storageServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return storageServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return storageServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return storageServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StorageService"
	handlerType := (*service.StorageService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func checkOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*service.StorageServiceCheckOrderArgs)

	err := handler.(service.StorageService).CheckOrder(ctx, realArg.OrderData)
	if err != nil {
		return err
	}

	return nil
}
func newStorageServiceCheckOrderArgs() interface{} {
	return service.NewStorageServiceCheckOrderArgs()
}

func newStorageServiceCheckOrderResult() interface{} {
	return service.NewStorageServiceCheckOrderResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CheckOrder(ctx context.Context, orderData *service.OrderData) (err error) {
	var _args service.StorageServiceCheckOrderArgs
	_args.OrderData = orderData
	var _result service.StorageServiceCheckOrderResult
	if err = p.c.Call(ctx, "CheckOrder", &_args, &_result); err != nil {
		return
	}
	return nil
}
