// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package service

import (
	"context"
	"fmt"
)

type OrderData struct {
	UserId    int32 `thrift:"UserId,1,required" frugal:"1,required,i32" json:"UserId"`
	ProductId int32 `thrift:"ProductId,2,required" frugal:"2,required,i32" json:"ProductId"`
}

func NewOrderData() *OrderData {
	return &OrderData{}
}

func (p *OrderData) InitDefault() {
}

func (p *OrderData) GetUserId() (v int32) {
	return p.UserId
}

func (p *OrderData) GetProductId() (v int32) {
	return p.ProductId
}
func (p *OrderData) SetUserId(val int32) {
	p.UserId = val
}
func (p *OrderData) SetProductId(val int32) {
	p.ProductId = val
}

func (p *OrderData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderData(%+v)", *p)
}

var fieldIDToName_OrderData = map[int16]string{
	1: "UserId",
	2: "ProductId",
}

type StorageService interface {
	CheckOrder(ctx context.Context, orderData *OrderData) (err error)
}

type StorageServiceCheckOrderArgs struct {
	OrderData *OrderData `thrift:"orderData,1,required" frugal:"1,required,OrderData" json:"orderData"`
}

func NewStorageServiceCheckOrderArgs() *StorageServiceCheckOrderArgs {
	return &StorageServiceCheckOrderArgs{}
}

func (p *StorageServiceCheckOrderArgs) InitDefault() {
}

var StorageServiceCheckOrderArgs_OrderData_DEFAULT *OrderData

func (p *StorageServiceCheckOrderArgs) GetOrderData() (v *OrderData) {
	if !p.IsSetOrderData() {
		return StorageServiceCheckOrderArgs_OrderData_DEFAULT
	}
	return p.OrderData
}
func (p *StorageServiceCheckOrderArgs) SetOrderData(val *OrderData) {
	p.OrderData = val
}

func (p *StorageServiceCheckOrderArgs) IsSetOrderData() bool {
	return p.OrderData != nil
}

func (p *StorageServiceCheckOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceCheckOrderArgs(%+v)", *p)
}

var fieldIDToName_StorageServiceCheckOrderArgs = map[int16]string{
	1: "orderData",
}

type StorageServiceCheckOrderResult struct {
}

func NewStorageServiceCheckOrderResult() *StorageServiceCheckOrderResult {
	return &StorageServiceCheckOrderResult{}
}

func (p *StorageServiceCheckOrderResult) InitDefault() {
}

func (p *StorageServiceCheckOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceCheckOrderResult(%+v)", *p)
}

var fieldIDToName_StorageServiceCheckOrderResult = map[int16]string{}
