// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package service

import (
	"context"
	"fmt"
)

type OrderData struct {
	UserId    int32 `thrift:"UserId,1,required" frugal:"1,required,i32" json:"UserId"`
	ProductId int32 `thrift:"ProductId,2,required" frugal:"2,required,i32" json:"ProductId"`
}

func NewOrderData() *OrderData {
	return &OrderData{}
}

func (p *OrderData) InitDefault() {
}

func (p *OrderData) GetUserId() (v int32) {
	return p.UserId
}

func (p *OrderData) GetProductId() (v int32) {
	return p.ProductId
}
func (p *OrderData) SetUserId(val int32) {
	p.UserId = val
}
func (p *OrderData) SetProductId(val int32) {
	p.ProductId = val
}

func (p *OrderData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderData(%+v)", *p)
}

var fieldIDToName_OrderData = map[int16]string{
	1: "UserId",
	2: "ProductId",
}

type CheckService interface {
	CheckOrder(ctx context.Context, orderData *OrderData) (err error)
}

type CheckServiceCheckOrderArgs struct {
	OrderData *OrderData `thrift:"orderData,1,required" frugal:"1,required,OrderData" json:"orderData"`
}

func NewCheckServiceCheckOrderArgs() *CheckServiceCheckOrderArgs {
	return &CheckServiceCheckOrderArgs{}
}

func (p *CheckServiceCheckOrderArgs) InitDefault() {
}

var CheckServiceCheckOrderArgs_OrderData_DEFAULT *OrderData

func (p *CheckServiceCheckOrderArgs) GetOrderData() (v *OrderData) {
	if !p.IsSetOrderData() {
		return CheckServiceCheckOrderArgs_OrderData_DEFAULT
	}
	return p.OrderData
}
func (p *CheckServiceCheckOrderArgs) SetOrderData(val *OrderData) {
	p.OrderData = val
}

func (p *CheckServiceCheckOrderArgs) IsSetOrderData() bool {
	return p.OrderData != nil
}

func (p *CheckServiceCheckOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckServiceCheckOrderArgs(%+v)", *p)
}

var fieldIDToName_CheckServiceCheckOrderArgs = map[int16]string{
	1: "orderData",
}

type CheckServiceCheckOrderResult struct {
}

func NewCheckServiceCheckOrderResult() *CheckServiceCheckOrderResult {
	return &CheckServiceCheckOrderResult{}
}

func (p *CheckServiceCheckOrderResult) InitDefault() {
}

func (p *CheckServiceCheckOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckServiceCheckOrderResult(%+v)", *p)
}

var fieldIDToName_CheckServiceCheckOrderResult = map[int16]string{}
