EtcdConfig:
  key: /config/storage
  host: 127.0.0.1
  port: 2379
ResolverConfig:
  namespace: test
  env: dev
  service_name: storage
RegisterConfig:
  namespace: test
  env: dev
  service_name: storage
  instance_id: storage-1
  address: 127.0.0.1:8888
  ttl: 30