RabbitMQConfig:
 username: SCDOMM
 password: 114514
 host: 127.0.0.1
 port: 5672
 vhost: CQUPT7G
MySQLConfig:
 username: xxx
 password: 114514
 host: 127.0.0.1
 port: 3306
 dbname: xxx
 charset: utf8mb4&parseTime=True&loc=Local"
RedisConfig:
 host: 127.0.0.1
 port: 6379
 password: 114514
 db: 0